protected/models/GroupType.php
<?php
/**
 * Group Type Model.
 *
 * @author  Asmaa
 * @version version:1.0
 * @since   version 1.0
 */

Yii::import('application.models._base.BaseGroupType');

/**
 * Group Type Model Class.
 *
 * @author  Asmaa
 * @version version:1.0
 * @since   version 1.0
 */
class GroupType extends BaseGroupType
{
	public static function model($className = __CLASS__)
	{
		return parent::model($className);
	}
	/**
	 * Gets the group type icon full path
	 *
	 * @param string $icon Icon's name
	 * @author Asmaa
	 * @return string path of the icon
	 */
	public function getGroupTypeIconPath($icon)
	{
		return Yii::app()->baseUrl . Config::model()->getConfigValue('group_type_icon') . $icon;
	}

}

protected/controllers/PageController.php
<?php
/**
 * Page Controller.
 *
 * @author  Asmaa
 * @version version:1.0
 * @since   version 1.0
 */

/**
 * Page Controller Class.
 *
 * @author  Asmaa
 * @version version:1.0
 * @since   version 1.0
 */
class PageController extends GxController
{

	/**
	 * Filters
	 *
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations.
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 *
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
				array(
						'allow',
						// allow all users to perform 'index' and 'view' actions.
						'actions' => array(
							'index', 'view'
						),
						'users' => array(
							'*'
						),
				),
				array(
						'allow',
						// allow authenticated user to perform 'create' and 'update' actions.
						'actions' => array(
								'create',
								'update',
								'followPage',
								'unfollowPage',
								'viewCalendar',
								'viewPosts',
								'viewFollowers',
								'viewPhotos',
								'delete',
								'edit'
						),
						'users' => array(
							'@'
						),
				),
				array(
						'allow',
						// allow admin user to perform 'admin' and 'delete' actions.
						'actions' => array(
							'admin'
						),
						'users' => array(
							'admin'
						),
				),
				array(
					'deny', // deny all users.
					'users' => array(
						'*'
					),
				),
		);
	}
	/**
	 * Rendering the page view and all of its related data
	 *
	 * @author Asmaa
	 * @param integer $id Id of the page to be viewed
	 * @return void
	 */
	public function actionView($id)
	{
		if (Yii::app()->getRequest()->getIsAjaxRequest())
		{
			$this
					->renderPartial('_pageView',
									array(
									'model' => $this->loadModel($id, 'Page'),
									'admins' => PageAdmin::model()->getPageAdmins($id),
									'isFollowing' => (!Yii::app()->user->isGuest)
											? UserFollowPage::model()
													->isFollowingPage($id, Yii::app()->user->id)
											: false,
									),
									false,
									true);
		}
		else
		{
			$this
					->render('view',
							 array(
									'model' => $this->loadModel($id, 'Page'),
									'admins' => PageAdmin::model()->getPageAdmins($id),
									'isFollowing' => (!Yii::app()->user->isGuest)
											? UserFollowPage::model()
													->isFollowingPage($id, Yii::app()->user->id)
											: false,
							 ));
		}
	}

	/**
	 * Displays a particular page's posts.
	 *
	 * @param integer $id Id of the page to be viewed
	 * @author Asmaa
	 * @return void
	 */
	public function actionViewPosts($id)
	{
		$data = array();
		$data["model"] = $this->loadModel($id, 'Page');
		$this->renderPartial('page-navigation/_pagePosts', $data, false, true);
	}

	/**
	 * Displays a particular page's followers
	 *
	 * @param integer $id Id of the page to be viewed
	 * @author Asmaa
	 * @return void
	 */
	public function actionViewFollowers($id)
	{
		$data["followers"] = UserFollowPage::model()->getPageFollowers($id);
		$data["pageid"] = $id;
		$this->renderPartial('page-navigation/_pageFollowers', $data, false, true);
	}

	/**
	 * Displays a particular page's photo album.
	 *
	 * @param integer $id Id of the page to be viewed
	 * @author Asmaa
	 * @return void
	 */
	public function actionViewPhotos($id)
	{

		$data = array();
		$data["model"] = $this->loadModel($id, 'Page');
		$this->renderPartial('page-navigation/_pagePhotos', $data, false, true);
	}

	/**
	 * Displays a particular page's calendar.
	 *
	 * @param integer $id Id of the page to be viewed
	 * @author Asmaa
	 * @return void
	 */
	public function actionViewCalendar($id)
	{
		$data = array();
		$data["model"] = $this->loadModel($id, 'Page');
		$this->renderPartial('page-navigation/_pageCalendar', $data, false, true);
	}

	/**
	 * Create a page
	 *
	 * @param integer $groupId Group id that the newely created page belongs to
	 * @author Asmaa
	 * @return void
	 */
	public function actionCreate($groupId = null)
	{
		$model = new Page;
		$model->scenario = 'create';
		if (!($groupId == null))
		{
			$model->group_id = $groupId;
		}

		if (isset($_POST['Page']))
		{
			$model->setAttributes($_POST['Page']);
			$model->creator_id = Yii::app()->user->id;
			if ($model->save())
			{
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
				{
					if (PageAdmin::model()->addAdmin($model->page_id, $model->creator_id))
						$this->redirect(array(
									'view', 'id' => $model->page_id
								));
				}
			}
		}

		$this->render('create', array(
					'model' => $model
				));
	}

	/**
	 * Editing page's data
	 *
	 * @param integer $id Id of the page to be edited
	 * @author Asmaa
	 * @return void
	 */
	public function actionEdit($id)
	{
		$model = $this->loadModel($id, 'Page');
		$data = array();
		$model->scenario = 'edit';
		if (isset($_POST['Page']))
		{
			$model->setAttributes($_POST['Page']);
			if ($model->save())
			{
				Yii::app()->user->setFlash('success', Yii::t('app', 'Your Edits are saved :)'));
				$this->actionView($id);
			}
			else
			{
				$data["model"] = $model;
				$this->renderPartial('_form', $data, false, true);
			}
		}
		else
		{
			$data["model"] = $model;
			$this->renderPartial('_form', $data, false, true);
		}
	}

	/**
	 * Take the page down
	 *
	 * First remove all page's followers and 2- & admins before deleting the page itself.
	 * If this page is the last one that its group holds then deleting
	 * it means that it's group pages_enabled option=0
	 *
	 * @param integer $id Id of the page to be deleted
	 * @author Asmaa
	 * @throws CHttpException For null model.
	 * @return void
	 */
	public function actionDelete($id)
	{
		// Only page admin can take a page down.
		if (PageAdmin::model()->isAdmin($id, Yii::app()->user->id))
		{

			$model = $this->loadModel($id, 'Page');
			$name = $model->name;
			if ($model === null)
			{
				throw new CHttpException(404, Yii::t('app', 'The requested page does not exist.'));
			}
			else
			{

				$groupId = $model->group_id;
				// 1. delete all of the page followers.
				if (UserFollowPage::model()->deleteAllFollowers($model->page_id)
				// 2. delete all of the page admins.
 && PageAdmin::model()->deleteAllAdminsOfPage($model->page_id)
				// 3. delete the page itself.
 && $model->delete())
				{
					Yii::app()->user
							  ->setFlash('success',
										 Yii::t('app', 'Page ') . $name
											. Yii::t('app', ' is deleted successfully'));
					$group = $this->loadModel($groupId, 'Group');
					// If this page is the last one that its group holds then deleting
					// it means that it's group pages_enabled option=0.
					if (count($group->pages) == 0)
					{
						$group->pages_enabled = 0;
						$group->save();
					}
					$this->redirect(array(
								'group/' . $groupId
							));
				}
				$this->redirect(array(
							'view', $id
						));
			}

		}
		else
		{
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
		}
	}

	/**
	 * User follows a page
	 *
	 * @param integer $pageId The followed page id
	 * @param integer $userId The follower user id
	 * @author Asmaa
	 * @return void
	 */
	public function actionFollowPage($pageId, $userId)
	{
		$model = new UserFollowPage();
		$model->following_user_id = $userId;
		$model->followed_page_id = $pageId;

		if ($model->save())
		{
			$data["pageId"] = $pageId;
			$data["isFollowing"] = UserFollowPage::model()
					->isFollowingPage($pageId, Yii::app()->user->id);
			$this->renderPartial('_followPage', $data, false, true);
		}
	}

	/**
	 * User unfollows a page
	 *
	 * @param integer $pageId The unfollowed page id
	 * @param integer $userId The follower user id
	 * @author Asmaa
	 * @throws CHttpException For null models.
	 * @return void
	 */
	public function actionUnfollowPage($pageId, $userId)
	{
		$model = UserFollowPage::model()
				->findByAttributes(array(
								   'followed_page_id' => $pageId, 'following_user_id' => $userId
								   ));
		if ($model === null)
		{
			throw new CHttpException(404, Yii::t('app', 'The requested page does not exist.'));
		}
		else
		{
			if ($model->delete())
			{
				$data["pageId"] = $pageId;
				$data["isFollowing"] = false;
				$this->renderPartial('_followPage', $data, false, true);
			}
		}
	}

	/**
	 * Yii default Index action
	 *
	 * @author Yii
	 * @return void
	 */
	public function actionIndex()
	{
		$dataProvider = new CActiveDataProvider('Page');
		$this->render('index', array(
					'dataProvider' => $dataProvider,
				));
	}

	/**
	 * Yii default Admin action
	 *
	 * @author Yii
	 * @return void
	 */
	public function actionAdmin()
	{
		$model = new Page('search');
		$model->unsetAttributes();

		if (isset($_GET['Page']))
		{
			$model->setAttributes($_GET['Page']);
		}

		$this->render('admin', array(
					'model' => $model,
				));
	}
}

protected/controllers/UserController.php
<?php

class UserController extends Controller
{

    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';

    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow', // allow all users to perform 'index' and 'view' actions
                'actions' => array('index', 'view'),
                'users' => array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions' => array('create', 'update', 'followUser', 'unfollowUser'),
                'users' => array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('admin', 'delete'),
                'users' => array('admin'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id)
    {

        $this->render('view', array(
            'model' => $this->loadModel($id),
            'isFollowing' => (!Yii::app()->user->isGuest)? UserFollowUser::model()->isFollowingUser($id): false,
        ));
    }

    /**
     * The logged in user can follow the user defined by $id
     * 
     * @param integer $id followed user id 
     * @author Asmaa
     * @return void
     */
    public function actionFollowUser($id)
    {
        $model = new UserFollowUser();
        $model->following_user_id = Yii::app()->user->id;
        $model->followed_user_id = $id;
        
        if ($model->save())
        {
        	
	        $data["id"] = $id;
	        $data["isFollowing"] = UserFollowUser::model()->isFollowingUser($id);
	        $this->renderPartial('_followUser', $data, false, true);
        }
    }

    /**
     * The logged in user can unfollow the user defined by $id
     * 
     * @param integer $id unfollowed user id 
     * @author Asmaa
     * @return void
     */
    public function actionUnfollowUser($id)
    {
        $following = Yii::app()->user->id;
        $model = UserFollowUser::model()->findByAttributes(array('following_user_id'=>$following,'followed_user_id'=>$id));
        if ($model === null)
        {
            throw new CHttpException(404, 'The requested page does not exist.');
        }
        elseif ($model->delete())
        {
	        $data["id"] = $id;
	        $data["isFollowing"] = UserFollowUser::model()->isFollowingUser($id);
	        $this->renderPartial('_followUser', $data, false, true);
        }
    }
   
    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate()
    {
        $model = new User;

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['User']))
        {
            $model->attributes = $_POST['User'];
            if ($model->save())
                $this->redirect(array('view', 'id' => $model->user_id));
        }

        $this->render('create', array(
            'model' => $model,
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id)
    {
        $this->loadModel($id)->delete();

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['User']))
        {
            $model->attributes = $_POST['User'];
            if ($model->save())
                $this->redirect(array('view', 'id' => $model->user_id));
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id)
    {
        if (Yii::app()->request->isPostRequest)
        {
            // we only allow deletion via POST request
            $this->loadModel($id)->delete();

            // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
            if (!isset($_GET['ajax']))
                $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
        }
        else
            throw new CHttpException(400, 'Invalid request. Please do not repeat this request again.');
    }

    /**
     * Lists all models.
     */
    public function actionIndex()
    {
        $dataProvider = new CActiveDataProvider('User');
        $this->render('index', array(
            'dataProvider' => $dataProvider,
        ));
    }

    /**
     * Manages all models.
     */
    public function actionAdmin()
    {
        $model = new User('search');
        $model->unsetAttributes();  // clear any default values
        if (isset($_GET['User']))
            $model->attributes = $_GET['User'];

        $this->render('admin', array(
            'model' => $model,
        ));
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer the ID of the model to be loaded
     */
    public function loadModel($id)
    {
        $model = User::model()->findByPk($id);
        if ($model === null)
            throw new CHttpException(404, 'The requested page does not exist.');
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param CModel the model to be validated
     */
    protected function performAjaxValidation($model)
    {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'user-form')
        {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }

}

protected/views/group/group-navigation/_groupCalendar.php
<?php
/**
 * Group calendar viewer inside the group.
 *
 * @todo    Place a calendar here
 * @author  Asmaa
 * @version version: 1.0
 */

?>
<?php
// Calendar widget to be placed here.
echo "Hat el calendar ya islaaaaaam :O";
  ?>

protected/views/group/group-navigation/_groupFiles.php
<?php
/**
 * Group files manager viewer inside the group.
 *
 * @todo    Place a file manager here
 * @author  Asmaa
 * @version version: 1.0
 */

?>
<?php
// Files widget to be placed here.
echo "Group ka7yan ma3ndosh files :P";

?>

protected/views/group/group-navigation/_groupMembers.php
<?php
/**
 * Group members viewer inside the group.
 *
 * @author  Asmaa
 * @version version: 1.0
 */

?>
<?php

// Group Members widget to be placed here .
echo "<h4>" . Yii::t('app', 'Member|Members', count($members)) . "</h4>";
foreach ($members as $member)
{

	echo "<div style='padding:5px;margin:5px;border: 1px solid #F0F0F0'>";

	echo CHtml::image($member->profile_picture,
					  $member->first_name,
					  array(
					  'style' => 'width:64px;height:auto;float:left;'
					  ));
	echo "<div>";
	echo CHtml::link($member->first_name . " " . $member->last_name,
					 CController::createUrl('user/view', array(
					 'id' => $member->user_id
					 )));
	if (GroupMember::model()->isAdmin($member->user_id, $groupId))
	{
		echo "<i>" . Yii::t('app', '(Admin)') . "</i>";
	}
	elseif (GroupMember::model()->isAdmin(Yii::app()->user->id, $groupId))
	{
		/*
		//1. remove from group -ajax
		//2. set as admin - ajax
		//echo "<span id ='admin-".$member->user_id."'>";
		//        echo CHtml::link (Yii::t('app', 'set him as admin')
		//        , $this->createUrl('setAdmin',
		 * array('grp_id'=>$groupId, 'user_id'=>$member->user_id)));
		//       // echo "<span id='admin-".$member->user_id."'>";
		//        echo CHtml::ajaxButton(Yii::t('app', 'set him as admin')
		//        , $this->createUrl('setAdmin',
		 * array('grp_id'=>$groupId, 'user_id'=>$member->user_id))
		//        ,array('success' =>
		 * 'function(){$("#admin-' . $member->user_id . '").html("<i>(Admin)</i>");}')
		//
		//                );
		// echo "</span>";
		 *
		 */
	}
	echo "<br /><i>" . $member->info . "</i>";
	echo "</div><div class='clear-both'></div>";

	echo "</div>";
}
  ?>

protected/views/group/group-navigation/_groupPages.php
<?php
/**
 * Group pages viewer inside the group.
 *
 * @todo    To be edited later for premium subscribers
 * @author  Asmaa
 * @version version: 1.0
 */

?>
<?php

// Pages widget to be placed here.
if (count($pages) == 0)
{
	echo Yii::t('app', 'This group has no pages yet      ');

}
else
{
	foreach ($pages as $page)
	{
		echo "<div style='border: 1px solid #F0F0F0; padding: 10px;margin: 5px;'>";
		echo CHtml::image($page->icon, $page->name);
		echo CHtml::link($page->name,
						 $this
						 ->createUrl('page/view', array(
							'id' => $page->page_id
						 )));
		echo "<br />";
		echo "<i>" . $page->info . "</i>";
		echo "</div>";
		echo "<br />";
	}

}
echo "<br />";
echo CHtml::link(Yii::t('app', 'Create page now!'),
				 $this->createUrl('page/create', array(
					  'groupId' => $groupId
					  )));
  ?>

protected/views/group/group-navigation/_groupPhotos.php
<?php
/**
 * Group photos viewer inside the group.
 *
 * @todo    Place a photo widget here
 * @author  Asmaa
 * @version version: 1.0
 */

?>
<?php
// Photo Album widget to be placed here.
echo "Group ka7yan ma3ndosh photos :P";

?>

protected/views/group/group-navigation/_groupPosts.php
<?php
/**
 * Group posts viewer inside the group.
 *
 * @todo    Place a wall widget here
 * @author  Asmaa
 * @version version: 1.0
 */

?>
<?php
// EDIT THE _groupView.
// posts widget to be placed here .

echo "Group Posts mafehash 7aga alla y 5ayeb elly 3malha :D";

?>

protected/views/group/group-navigation/_groupTasks.php
<?php
/**
 * Group tasks viewer inside the group.
 *
 * @todo    Place a task widget here
 * @author  Asmaa
 * @version version: 1.0
 */

?>
<?php
// Tasks widget to be placed here.
echo "Hoooooooraaaaaaaay emty tasks ya fashalaaaaa";

?>

protected/views/group/group-navigation/_membersForm.php
<?php
/**
 * Group add / invite members form viewer inside the group.
 *
 * @author  Asmaa
 * @version version: 1.0
 */

?>
<div id="group-wrapper">

<div class="form">
<?php
$form = $this
		->beginWidget('CActiveForm',
					  array(
						'id' => 'invite-form',
						'enableAjaxValidation' => false,
						'enableClientValidation' => true,
						'clientOptions' => array(
							'validateOnSubmit' => true
						),
					  ));
				  ?>

<p class="note"><span class="required">
<?php
echo Yii::t('app',
			'Note that you can only invite people
			you are following and they are follwing you back too only');
									   ?>
</span></p>
<?php echo $form->errorSummary($model); ?>
<div class="row buttons">
<?php
$noInv = true;
if (count($people) == 0)
{
	$noInv = false;
}
else
{
	foreach ($people as $invited)
	{

		echo "<div style='padding:5px;margin:5px;border: 1px solid #F0F0F0'>";
		if (GroupMember::model()->isWaitingApproval($invited->user_id, $model->group_id))
		{
			echo "<i>" . Yii::t('app', '(Waiting admin approval)') . "</i>";
		}
		elseif (GroupMember::model()->isInvited($invited->user_id, $model->group_id))
		{
			echo "<i>" . Yii::t('app', '(Invitation is sent)') . "</i>";
		}
		elseif (GroupMember::model()->isAdmin($invited->user_id, $model->group_id))
		{
			echo "<i>" . Yii::t('app', '(Admin)') . "</i>";
		}
		elseif (GroupMember::model()->isMember($invited->user_id, $model->group_id))
		{
			echo "<i>" . Yii::t('app', '(Member)') . "</i>";
		}
		else
		{
			$noInv = false;
			echo CHtml::checkBox($invited->user_id, false);
		}
		echo CHtml::image($invited->profile_picture,
						  $invited->first_name,
						  array(
						  'style' => 'width:64px;height:auto;float:left;'
						  )) . "<div>"
				. CHtml::link($invited->first_name . " " . $invited->last_name,
							  CController::createUrl('user/view',
													 array(
													 'id' => $invited->user_id
													 ))) . "<br /><i>" . $invited->info
				. "</i></div><div class='clear-both'></div>";

		echo "</div>";
	}
}
						 ?></div>
<div class="row buttons">
<?php
if (!$noInv)
{
	echo CHtml::ajaxSubmitButton(Yii::t('app', 'Invite Selected'),
								 array(
								 'invite', 'id' => $model->group_id
								 ),
								 array(
								 'update' => '#group-wrapper',
								 'data' => 'js:$("#invite-form").serialize()',
								 'method' => 'post'
								 ));
}
						 ?></div>
<?php $this->endWidget(); ?></div>
<!-- form --></div>

protected/views/group/group-navigation/_pendingRequests.php
<?php
/**
 * Group pending requests for the admin viewer inside the group.
 *
 * Only Invitations requests are available
 *
 * @todo    Place the rest of pending requests
 * @author  Asmaa
 * @version version: 1.0
 */

?>
<div id="group-wrapper">
    <h4><?php echo Yii::t('app', 'Invitation Approval Requests'); ?></h4>
<?php
if (count($invReqs) == 0)
	echo Yii::t('app', 'No pending requests to show');
else
{
	foreach ($invReqs as $request)
	{
		echo "<div style='border: 1px solid #F0F0F0; padding: 10px;margin: 5px;' id='request-"
				. $request->user_id . "'>";
		echo CHtml::link($request->first_name . " " . $request->last_name,
						 CController::createUrl('user/view',
												array(
												'id' => $request->user_id
												)));

		echo CHtml::ajaxButton(Yii::t('app', 'Approve'),
							   $this
							   ->createUrl('approveInv',
										   array(
										   'groupId' => $groupId, 'userId' => $request->user_id
								)),
							   array(
							   'success' => 'function(){$("#request-' . $request->user_id
								. '").fadeOut("slow");}'
							   ));
		echo CHtml::ajaxButton(Yii::t('app', 'Cancel Request'),
							   $this
							   ->createUrl('cancelInv',
										   array(
										   'groupId' => $groupId, 'userId' => $request->user_id
								)),
							   array(
							   'success' => 'function(){$("#request-' . $request->user_id
								. '").fadeOut("medium");}'
							   ));
		echo "</div>";
	}
}
																		 ?>
</div>