protected/controllers/GroupController.php
<?php
/**
 * Group Controller.
 *
 * @author  Asmaa
 * @version version:1.0
 * @since   version 1.0
 */

/**
 * Group Controller Class.
 *
 * @author  Asmaa
 * @version version:1.0
 * @since   version 1.0
 */
class GroupController extends GxController
{
	/**
	 * Filters
	 *
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations.
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 *
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
				array(
						'allow',
						// allow authenticated user to perform 'create' and 'update' actions.
						'actions' => array(
								'create',
								'update',
								'viewInvitePeople',
								'edit',
								'index',
								'view',
								'viewPartial',
								'viewPosts',
								'viewFiles',
								'viewMembers',
								'viewPhotos',
								'viewPages',
								'viewCalendar',
								'viewTasks',
								'viewRequests',
								'invite',
								'acceptInv',
								'declineInv',
								'approveInv',
								'cancelInv',
								'delete',
								'leaveGroup'
						),
						'users' => array(
							'@'
						),
				),
				array(
					'allow', // allow admin user to perform 'admin' and 'delete' actions.
					'actions' => array(
						'admin'
					), 'users' => array(
						'admin'
					),
				),
				array(
					'deny', // deny all users.
					'users' => array(
						'*'
					),
				),
		);
	}

	/**
	 * Registring scripts for the controller
	 *
	 * @author Asmaa
	 * @return void
	 */
	public function init()
	{
		Yii::app()->clientScript->registerCssFile(Yii::app()->baseUrl . '/css/group.css');
		Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . '/js/group.js');
	}

	/**
	 * Rendering the group view and all of its related data
	 *
	 * @author Asmaa
	 * @param integer $id Id of the group to be viewed
	 * @throws CHttpException For not authenticated users.
	 * @return void
	 */
	public function actionView($id)
	{
		if (GroupMember::model()->isAuthToView(Yii::app()->user->id, $id))
		{
			$data = array();
			$data = Group::model()->getGroupStatistics($id);
			if (Yii::app()->getRequest()->getIsAjaxRequest())
			{
				$this->renderPartial('_groupView', $data, false, true);
			}
			else
			{
				$this->render('view', $data);
			}
		}
		else
		{
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
		}
	}

	/**
	 * Displays a particular group's posts.
	 *
	 * @param integer $id Id of the group to view its posts
	 * @author Asmaa
	 * @throws CHttpException For not authenticated users.
	 * @return void
	 */
	public function actionViewPosts($id)
	{
		if (GroupMember::model()->isAuthToView(Yii::app()->user->id, $id))
		{
			$data = array();
			$data["model"] = $this->loadModel($id, 'Group');
			$this->renderPartial('group-navigation/_groupPosts', $data, false, true);
		}
		else
		{
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
		}
	}

	/**
	 * Displays a particular group's files.
	 *
	 * @param integer $id Id of the group to view its files
	 * @author Asmaa
	 * @throws CHttpException For not authenticated users.
	 * @return void
	 */
	public function actionViewFiles($id)
	{
		if (GroupMember::model()->isAuthToView(Yii::app()->user->id, $id))
		{
			$data = array();
			$data["model"] = $this->loadModel($id, 'Group');
			$this->renderPartial('group-navigation/_groupFiles', $data, false, true);
		}
		else
		{
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
		}
	}

	/**
	 * Displays a particular group's members including the administrator.
	 *
	 * @param integer $id Id of the group to view its members
	 * @author Asmaa
	 * @todo get all members of the group inclusing admins
	 * @throws CHttpException For not authenticated users.
	 * @return void
	 */
	public function actionViewMembers($id)
	{
		if (GroupMember::model()->isAuthToView(Yii::app()->user->id, $id))
		{
			$data["members"] = GroupMember::model()->getGroupMembers($id);
			$data["groupId"] = $id;
			$this->renderPartial('group-navigation/_groupMembers', $data, false, true);
		}
		else
		{
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
		}
	}

	/**
	 * Displays a particular group's photo album.
	 *
	 * @param integer $id Id of the group to view its photos
	 * @author Asmaa
	 * @throws CHttpException For not authenticated users.
	 * @return void
	 */
	public function actionViewPhotos($id)
	{
		if (GroupMember::model()->isAuthToView(Yii::app()->user->id, $id))
		{
			$data = array();
			$data["model"] = $this->loadModel($id, 'Group');
			$this->renderPartial('group-navigation/_groupPhotos', $data, false, true);
		}
		else
		{
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
		}
	}

	/**
	 * Displays a particular group's pages.
	 *
	 * @param integer $id Id of the group to view its pages
	 * @author Asmaa
	 * @todo Get pages that belong to this group, this option is only available for premium
	 * subscribers
	 * @throws CHttpException For not authenticated users.
	 * @return void
	 */
	public function actionViewPages($id)
	{
		if (GroupMember::model()->isAuthToView(Yii::app()->user->id, $id))
		{
			$data = array();
			$data["pages"] = Group::model()->getGroupPages($id);
			$data["groupId"] = $id;
			$this->renderPartial('group-navigation/_groupPages', $data, false, true);
		}
		else
		{
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
		}
	}

	/**
	 * Displays a particular group's calendar.
	 *
	 * @param integer $id Id of the group to view its calendar
	 * @author Asmaa
	 * @throws CHttpException For not authenticated users.
	 * @return void
	 */
	public function actionViewCalendar($id)
	{
		if (GroupMember::model()->isAuthToView(Yii::app()->user->id, $id))
		{
			$data = array();
			$data["model"] = $this->loadModel($id, 'Group');
			$this->renderPartial('group-navigation/_groupCalendar', $data, false, true);
		}
		else
		{
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
		}

	}

	/**
	 * Displays a particular group's tasks.
	 *
	 * @param integer $id Id of the group to view its tasks
	 * @author Asmaa
	 * @throws CHttpException For not authenticated users.
	 * @return void
	 */
	public function actionViewTasks($id)
	{
		if (GroupMember::model()->isAuthToView(Yii::app()->user->id, $id))
		{
			$data = array();
			$data["model"] = $this->loadModel($id, 'Group');
			$this->renderPartial('group-navigation/_groupTasks', $data, false, true);
		}
		else
		{
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
		}
	}

	/**
	 * Displays a particular requests sent to the admin page 'group-navigation/_pendingRequests'
	 *
	 * @param integer $id Id of the group to view its pending requests
	 * @author Asmaa
	 * @todo get all pending invitations from the group_members table only until this version
	 * @throws CHttpException For not authenticated users.
	 * @return void
	 */
	public function actionViewRequests($id)
	{
		if (GroupMember::model()->isAuthToView(Yii::app()->user->id, $id))
		{
			$data = array();
			$data["groupId"] = $id;
			$pendingInv = GroupMember::model()->getPendingInvitations($id);
			$models = array();

			if (!($pendingInv == null))
			{
				foreach ($pendingInv as $req)
				{
					$models[] = User::model()->findByPk($req->user_id);
				}
			}
			$data["invReqs"] = $models;
			$this->renderPartial('group-navigation/_pendingRequests', $data, false, true);
		}
		else
		{
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
		}
	}

	/**
	 * Renders the view of inviting people for a particular group
	 *
	 * @param integer $id Id of the group to view its invite people form
	 * @author Asmaa
	 * @todo load all user models of people who the _logged in_ user is following and they
	 * are following him back to be changed on friendship relation
	 * @return void
	 */
	public function actionViewInvitePeople($id)
	{
		$model = $this->loadModel($id, 'Group');
		$data = array();
		$data["model"] = $model;
		$people = UserFollowUser::model()->getFollowingEachOther(Yii::app()->user->id);
		$data["people"] = $people;

		$this->renderPartial('_invitePeople', $data, false, true);
	}

	/**
	 * The logged in user accepts invitation and this updates his group membership
	 *
	 * Update the group membership of the logged-in user and set the pending field to 0 so
	 * he becomes a final group member
	 *
	 * @param integer $id Id of the group
	 * @author Asmaa
	 * @return void
	 */
	public function actionAcceptInv($id)
	{
		$userid = Yii::app()->user->id;
		$model = GroupMember::model()
				->findByAttributes(array(
					'group_id' => $id, 'user_id' => $userid
				));
		$model->pending = 0;
		if ($model->save())
		{
			Yii::app()->user->setFlash('success', Yii::t('app', 'Welcome! :) '));
			$this->redirect(array(
						'view', 'id' => $id
					));
		}
	}

	/**
	 * Invited user has the ability to decline invitations sent to him
	 * If declining is successful, the browser will be redirected to the 'site/view' page.
	 *
	 * @param integer $id Id of the group
	 * @author Asmaa
	 * @return void
	 */
	public function actionDeclineInv($id)
	{
		if ($this->actionCancelInv(Yii::app()->user->id, $id))
		{
			$this->redirect(array(
						'site/index'
					));
		}
	}

	/**
	 * Creating the invitations to join group denoted by $id to be sent to the user
	 *
	 * If the invitation request is created by admin the request is sent to the user directly,
	 * elsewise it will wait for admin approval
	 *
	 * @param integer $id Group id
	 * @author Asmaa
	 * @return void
	 */
	public function actionInvite($id)
	{
		// Invitations by the admin is approved automatically.
		$approved = (GroupMember::model()->isAdmin(Yii::app()->user->id, $id)) ? 1 : 0;
		// only user ids are sent.
		$invited = array_keys($_POST);

protected/controllers/UserController.php
<?php

class UserController extends Controller
{

    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';

    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow', // allow all users to perform 'index' and 'view' actions
                'actions' => array('index', 'view'),
                'users' => array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions' => array('create', 'update', 'followUser', 'unfollowUser'),
                'users' => array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('admin', 'delete'),
                'users' => array('admin'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id)
    {

        $this->render('view', array(
            'model' => $this->loadModel($id),
            'isFollowing' => (!Yii::app()->user->isGuest)? UserFollowUser::model()->isFollowingUser($id): false,
        ));
    }

    /**
     * The logged in user can follow the user defined by $id
     * 
     * @param integer $id followed user id 
     * @author Asmaa
     * @return void
     */
    public function actionFollowUser($id)
    {
        $model = new UserFollowUser();
        $model->following_user_id = Yii::app()->user->id;
        $model->followed_user_id = $id;
        
        if ($model->save())
        {
        	
	        $data["id"] = $id;
	        $data["isFollowing"] = UserFollowUser::model()->isFollowingUser($id);
	        $this->renderPartial('_followUser', $data, false, true);
        }
    }

    /**
     * The logged in user can unfollow the user defined by $id
     * 
     * @param integer $id unfollowed user id 
     * @author Asmaa
     * @return void
     */
    public function actionUnfollowUser($id)
    {
        $following = Yii::app()->user->id;
        $model = UserFollowUser::model()->findByAttributes(array('following_user_id'=>$following,'followed_user_id'=>$id));
        if ($model === null)
        {
            throw new CHttpException(404, 'The requested page does not exist.');
        }
        elseif ($model->delete())
        {
	        $data["id"] = $id;
	        $data["isFollowing"] = UserFollowUser::model()->isFollowingUser($id);
	        $this->renderPartial('_followUser', $data, false, true);
        }
    }
   
    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate()
    {
        $model = new User;

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['User']))
        {
            $model->attributes = $_POST['User'];
            if ($model->save())
                $this->redirect(array('view', 'id' => $model->user_id));
        }

        $this->render('create', array(
            'model' => $model,
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id)
    {
        $this->loadModel($id)->delete();

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['User']))
        {
            $model->attributes = $_POST['User'];
            if ($model->save())
                $this->redirect(array('view', 'id' => $model->user_id));
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id)
    {
        if (Yii::app()->request->isPostRequest)
        {
            // we only allow deletion via POST request
            $this->loadModel($id)->delete();

            // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
            if (!isset($_GET['ajax']))
                $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
        }
        else
            throw new CHttpException(400, 'Invalid request. Please do not repeat this request again.');
    }

    /**
     * Lists all models.
     */
    public function actionIndex()
    {
        $dataProvider = new CActiveDataProvider('User');
        $this->render('index', array(
            'dataProvider' => $dataProvider,
        ));
    }

    /**
     * Manages all models.
     */
    public function actionAdmin()
    {
        $model = new User('search');
        $model->unsetAttributes();  // clear any default values
        if (isset($_GET['User']))
            $model->attributes = $_GET['User'];

        $this->render('admin', array(
            'model' => $model,
        ));
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer the ID of the model to be loaded
     */
    public function loadModel($id)
    {
        $model = User::model()->findByPk($id);
        if ($model === null)
            throw new CHttpException(404, 'The requested page does not exist.');
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param CModel the model to be validated
     */
    protected function performAjaxValidation($model)
    {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'user-form')
        {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }

}

protected/views/page/_admins.php
<?php
/**
 * Page administrators inside page.
 *
 * @author  Asmaa
 * @version version: 1.0
 */

?>
<div style='border: 1px solid #F0F0F0; padding: 10px;margin: 5px;'>
    <h4><?php echo Yii::t('app', 'Admins'); ?></h4>
<?php
foreach ($admins as $admin)
{
	echo CHtml::link($admin->getFullName(),
					 $this->createUrl('user/view', array(
						  'id' => $admin->user_id
						  )));
	echo "<br />";
}
				   ?>
</div>

protected/views/page/_followPage.php
<?php
/**
 * Follow page button.
 *
 * @todo    Place a wall widget here
 * @author  Asmaa
 * @version version: 1.0
 */

?>
<div id="follow">
<?php
if (!$isFollowing)
{

	echo CHtml::ajaxButton(Yii::t('app', 'follow'),
						   CController::createUrl('page/followPage',
												  array(
												  'pageId' => $pageId,
												  'userId' => Yii::app()->user->id
												  )),
						   array(
						   'update' => '#follow'
						   ),
						   array(
						   'id' => 'send-link-' . uniqid()
						   ));
}
else
{
	echo CHtml::ajaxButton(Yii::t('app', 'unfollow'),
						   CController::createUrl('page/unfollowPage',
												  array(
												  'pageId' => $pageId,
												  'userId' => Yii::app()->user->id
												  )),
						   array(
						   'update' => '#follow'
						   ),
						   array(
						   'id' => 'send-link-' . uniqid()
						   ));
}
				 ?>
</div>

protected/views/page/_form.php
<?php
/**
 * Page update/create form.
 *
 * @author  Asmaa
 * @version version: 1.0
 */

?>
<div id="page-wrapper">
    <div class="form">
<?php
if (!$model->isNewRecord)
{
	echo "<h1>" . Yii::t('app', 'Edit') . "</h1>";
	echo CHtml::ajaxLink(Yii::t('app', '&larr; Back to the page'),
						 $this
						 ->createUrl('view', array(
						 'id' => $model->page_id
						 )),
						 array(
						 'update' => '#page-wrapper'
						 ),
						 array(
						 'id' => 'send-link-' . uniqid()
						 ));
	echo "<br />";
}
					  ?>
<?php
$form = $this
		->beginWidget('GxActiveForm',
					  array(
					  'id' => 'page-form', 'enableAjaxValidation' => false,
					  ));
						?>

        <p class="note">
            <?php echo Yii::t('app', 'Fields with'); ?>
             <span class="required">*</span>
             <?php echo Yii::t('app', 'are required'); ?>.
        </p>

        <?php echo $form->errorSummary($model); ?>

        <div class="row">
            <?php if ($model->scenario == 'create') : ?>
                  <?php echo $form->labelEx($model, 'group_id'); ?>
                  <?php echo $form
			->dropDownList($model, 'group_id', GxHtml::listDataEx(User::model()->getAdminGroups()));
																  ?>
                  <?php echo $form->error($model, 'group_id'); ?>
              <?php endif; ?>
        </div><!-- row -->
        <div class="row">
            <?php echo $form->labelEx($model, 'info'); ?>
              <?php echo $form->textField($model, 'info'); ?>
              <?php echo $form->error($model, 'info'); ?>
        </div><!-- row -->
        <div class="row">
            <?php echo $form->labelEx($model, 'name'); ?>
<?php
echo $form
		->textField($model, 'name', array(
			'maxlength' => 255
		));
														 ?>
              <?php echo $form->error($model, 'name'); ?>
        </div><!-- row -->
        <?php
        /*
        <div class="row">
            <?php //echo $form->labelEx($model,'icon'); ?>
              <?php //echo $form->textField($model, 'icon', array('maxlength' => 255)); ?>
              <?php //echo $form->error($model,'icon');  ?>
        </div><!-- row -->
        <div class="row">
            <?php //echo $form->labelEx($model,'cover'); ?>
              <?php // echo $form->textField($model, 'cover', array('maxlength' => 255)); ?>
              <?php //echo $form->error($model,'cover');  ?>
        </div><!-- row -->
	`	*/
        ?>
        <div class="row">
            <?php if ($model->scenario == 'create') : ?>
                  <?php echo $form->labelEx($model, 'type_id'); ?>
<?php
echo $form
			->dropDownList($model,
						   'type_id',
						   GxHtml::listDataEx(PageType::model()->findAllAttributes(null, true)));
																 ?>
                  <?php echo $form->error($model, 'type_id'); ?>
              <?php endif; ?>
        </div><!-- row -->

<?php
if ($model->isNewRecord)
	echo GxHtml::submitButton(Yii::t('app', 'Launch Now!'));
else
	echo CHtml::ajaxSubmitButton(Yii::t('app', 'Save'),
								 $this
								 ->createUrl('edit',
											 array(
											 'id' => $model->page_id
								 )),
								 array(
								 'update' => '#page-wrapper'
								 ),
								 array(
								 'id' => 'send-link-' . uniqid()
								 ));

$this->endWidget();
?>
    </div><!-- form -->
</div>

protected/views/page/_pageView.php
<?php
/**
 * Page partial viewer.
 *
 * @author  Asmaa
 * @version version: 1.0
 */

?>
<div id="page-wrapper">
    <?php if (Yii::app()->user->hasFlash('success')) : ?>
        <div class="flash-notice">
            <?php echo Yii::app()->user->getFlash('success'); ?>
        </div>
    <?php endif; ?>
      <?php if (Yii::app()->user->hasFlash('error')) : ?>
    <div class="flash-error"><?php echo Yii::app()->user->getFlash('error'); ?></div>
    <?php endif; ?>
     <?php echo CHtml::image($model->getPageIcon($model->icon), $model->name); ?>
    <h1>
<?php
echo CHtml::link(GxHtml::encode(GxHtml::valueEx($model)),
				 $this->createUrl('view', array(
					  'id' => $model->page_id
					  )));
		?></h1>
<?php
if (PageAdmin::model()->isAdmin($model->page_id, Yii::app()->user->id))
{
	echo "<i>" . Yii::t('app', "Under Group ")
			. CHtml::link(Group::model()->getGroupName($model->group_id),
						  $this
							->createUrl('group/view',
										array(
										'id' => $model->group_id
									))) . "</i>";
	echo "<br />";
	echo CHtml::link(Yii::t('app', "Take this page down"),
					 $this->createUrl('delete', array(
						  'id' => $model->page_id
						  ))) . " | ";
	echo CHtml::ajaxLink(Yii::t('app', "Edit Info"),
						 $this->createUrl('edit', array(
							  'id' => $model->page_id
							  )),
						 array(
						 'update' => '#page-wrapper'
						 ),
						 array(
						 'id' => 'send-link-' . uniqid()
						 ));
	echo "<br />";
	$this->renderPartial('_admins', array(
				'admins' => $admins
			));
}
			   ?>
<?php
if ((!Yii::app()->user->isGuest)
		&& (!PageAdmin::model()->isAdmin($model->page_id, Yii::app()->user->id))) :
		 ?>
        <div id="follow">
<?php
if (!$isFollowing)
		echo CHtml::ajaxButton(Yii::t('app', 'follow'),
							   CController::createUrl('page/followPage',
													  array(
													  'pageId' => $model->page_id,
													  'userId' => Yii::app()->user->id
													  )),
							   array(
							   'update' => '#follow'
							   ),
							   array(
							   'id' => 'send-link-' . uniqid()
							   ));
	else
		echo CHtml::ajaxButton(Yii::t('app', 'unfollow'),
							   CController::createUrl('page/unfollowPage',
													  array(
													  'pageId' => $model->page_id,
													  'userId' => Yii::app()->user->id
													  )),
							   array(
							   'update' => '#follow'
							   ),
							   array(
							   'id' => 'send-link-' . uniqid()
							   ));
						 ?>
        </div>
    <?php endif; ?>
    <div style="border: 1px solid #F0F0F0; padding: 10px;margin: 5px;">
        <i><?php echo $model->info; ?></i>
    </div>
    <?php echo CHtml::image($model->getPageCover($model->cover), $model->name); ?>

    <div style="border: 1px solid #F0F0F0; padding: 10px; margin: 5px;">
<?php
echo CHtml::ajaxLink(Yii::t('app', "Posts"),
					 $this->createUrl('viewPosts', array(
						  'id' => $model->page_id
						  )),
					 array(
					 'update' => '#page-content'
					 ),
					 array(
					 'id' => 'send-link-' . uniqid()
					 ));
echo " | "
		. CHtml::ajaxLink(Yii::t('app', "Followers"),
						  $this
						  ->createUrl('viewFollowers',
									  array(
									  'id' => $model->page_id
								)),
						  array(
						  'update' => '#page-content'
						  ),
						  array(
						  'id' => 'send-link-' . uniqid()
						  ));
echo " | "
		. CHtml::ajaxLink(Yii::t('app', "Photos"),
						  $this
						  ->createUrl('viewPhotos',
									  array(
									  'id' => $model->page_id
								)),
						  array(
						  'update' => '#page-content'
						  ),
						  array(
						  'id' => 'send-link-' . uniqid()
						  ));
echo " | "
		. CHtml::ajaxLink(Yii::t('app', "Calendar"),
						  $this
						  ->createUrl('viewCalendar',
									  array(
									  'id' => $model->page_id
								)),
						  array(
						  'update' => '#page-content'
						  ),
						  array(
						  'id' => 'send-link-' . uniqid()
						  ));
																		?>
    </div>
    <div id="page-content" style="border: 1px solid #F0F0F0; padding: 10px;margin: 5px;">
<?php
$this->renderPartial("page-navigation/_pagePosts", array(
			'model' => $model
		))
																						 ?>
    </div>
</div>

protected/views/page/_view.php
<div class="view">

	<?php echo GxHtml::encode($data->getAttributeLabel('page_id')); ?>:
	<?php echo GxHtml::link(GxHtml::encode($data->page_id), array('view', 'id' => $data->page_id)); ?>
	<br />

	<?php echo GxHtml::encode($data->getAttributeLabel('group_id')); ?>:
	<?php echo GxHtml::link(GxHtml::encode($data->group_id), array('group/view', 'id' => $data->group_id));?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('info')); ?>:
	<?php echo GxHtml::encode($data->info); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('name')); ?>
	<?php echo GxHtml::encode($data->name); ?>
	<br />
        <?php /*
	<?php //echo GxHtml::encode($data->getAttributeLabel('icon')); ?>
	<?php //echo GxHtml::encode($data->icon); ?>
	<br />
	<?php //echo GxHtml::encode($data->getAttributeLabel('cover')); ?>
	<?php //echo GxHtml::encode($data->cover); ?>
	<br />
	<?php //echo GxHtml::encode($data->getAttributeLabel('creation_date')); ?>
	<?php //echo GxHtml::encode($data->creation_date); ?>
	<br />
	<?php /*
	<?php echo GxHtml::encode($data->getAttributeLabel('last_edit_date')); ?>:
	<?php echo GxHtml::encode($data->last_edit_date); ?>
	<br />
         */ ?>
	<?php echo GxHtml::encode($data->getAttributeLabel('type_id')); ?>:
	<?php echo GxHtml::encode($data->type_id); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('creator_id')); ?>:
	<?php echo  GxHtml::link(GxHtml::encode($data->creator_id), array('user/view', 'id' => $data->creator_id));?>
	<br />


</div>